services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123!$
      MYSQL_DATABASE: expenses
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./expense_script_sql.sql:/docker-entrypoint-initdb.d/1.sql"

  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expenses
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password123!$
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./angular-start/
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mysql_data:
